// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
)

type Category struct {
	ID         int64          `json:"id"`
	Name       string         `json:"name"`
	CreatedAt  sql.NullTime   `json:"created_at"`
	CreatedBy  sql.NullString `json:"created_by"`
	ModifiedAt sql.NullTime   `json:"modified_at"`
	ModifiedBy sql.NullString `json:"modified_by"`
}

type User struct {
	ID         int64          `json:"id"`
	Username   string         `json:"username"`
	Password   string         `json:"password"`
	CreatedAt  sql.NullTime   `json:"created_at"`
	CreatedBy  sql.NullString `json:"created_by"`
	ModifiedAt sql.NullTime   `json:"modified_at"`
	ModifiedBy sql.NullString `json:"modified_by"`
}
